# Generated by Django 3.0.4 on 2021-05-29 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='auther',
            new_name='author',
        ),
    ]
